// Code generated by lister-gen. DO NOT EDIT.

package v1

// ServiceExportListerExpansion allows custom methods to be added to
// ServiceExportLister.
type ServiceExportListerExpansion interface{}

// ServiceExportNamespaceListerExpansion allows custom methods to be added to
// ServiceExportNamespaceLister.
type ServiceExportNamespaceListerExpansion interface{}
